chirp-community/chirp-community

back_end/src/main/java/com/chirp/community/controller/BoardController.java, back_end/src/main/java/com/chirp/community/model/BoardDto.java, back_end/src/main/java/com/chirp/community/model/request/BoardCreateRequest.java, back_end/src/main/java/com/chirp/community/model/request/BoardUpdateRequest.java, back_end/src/main/java/com/chirp/community/model/response/BoardReadResponse.java, back_end/src/main/java/com/chirp/community/service/BoardService.java
주어진 조건에 맞춰서 API 구현
- Record 를 이용해 DTO 구현
=> #12 - BoardController 생성 및 DTO 생성

back_end/src/main/java/com/chirp/community/controller/SiteUserController.java, back_end/src/main/java/com/chirp/community/model/SiteUserDto.java, back_end/src/main/java/com/chirp/community/model/request/SiteUserCreateRequest.java, back_end/src/main/java/com/chirp/community/model/request/SiteUserUpdateRequest.java, back_end/src/main/java/com/chirp/community/model/response/SiteUserReadResponse.java, back_end/src/main/java/com/chirp/community/service/SiteUserService.java
주어진 조건에 맞춰서 API 구현
- Record 를 이용해 DTO 구현
=> #18 - SiteUserController 및 DTO 구현

back_end/src/main/java/com/chirp/community/configuration/AuthenticationConfig.java
1. 실수로 filter를 적용시키는 부분을 주석처리 함.
=> #45 - JwtFilter 적용 안한 버그 수정

back_end/src/main/java/com/chirp/community/configuration/JpaAuditingConfig.java
- 기존의 문제점 Bean 중복 문제 대두.
- 해결 방안 JpaAuditingConfig에서 정의되었던 @EnableJpaAuditing 어노테이션 삭제.
=> #53 - @CreatedDate 가 작동하지 않는 버그

back_end/src/main/java/com/chirp/community/configuration/JpaAuditingConfig.java, back_end/src/main/java/com/chirp/community/model/SiteUserDto.java
- 기존의 문제점 Principal의 타입이 SiteUserDto인데 SiteUser로 강제 타입 변환을 시킴.
- 해결 방안 SiteUserDto로 변환하고 SiteUser로 타입 변환.
=> #70 - jpaAuditing 설정 버그 수정

frontend/src/ComponentsUsers/Header/css.css, frontend/src/ComponentsUsers/Header/index.js
1. 파란색의 링크 표시를 검은색으로 변경 ![image](https://github.com/chirp-community/chirp-community/assets/66674140/065fdb39-1164-4e52-9cd7-7997ab138a4c) ![image](https://github.com/chirp-community/chirp-community/assets/66674140/f56f984f-1443-4372-9e2e-48465397a4b8)
2. 불필요한 주석 처리 제거
=> #82 - header 컴포넌트 수정

frontend/src/ComponentsUsers/Login/css.css, frontend/src/ComponentsUsers/Login/index.js
1. 로그인 실패 시, 실패 원인을 에러 메시지 라벨에 띄움.
2. 로그인 성공 시, 이전 페이지로 넘어감.
3. 회원 가입 페이지로 넘어가는 부분 존재.
4. 로그인 성공 후, JWT 취득 시, LocalStorage에 저장.
=> #84 - 로그인 페이지 구현

back_end/src/main/java/com/chirp/community/exception/ExceptionHandlerController.java
입력된 값을 감지할 때, 알파벳만 인식하고 숫자를 인식하지 못하는 경우가 발생함.
Ex) 'user1' 라는 문자를 인식하지 못함.
[a-zA-Z]+
->
(.*) 로 변경.
=> #94 - ExceptionHandlerController 버그 수정

frontend/src/ComponentsUsers/Sheet/css.css, frontend/src/ComponentsUsers/Sheet/index.js
Card 컴포넌트와 외관은 같지만 Sheet는 너비가 일정치 않고 자식 요소에 따라 유연하게 조절된다.
=> #100 - Sheet 컴포넌트 추가

frontend/src/utils/index.js
- hasSomethingInString : 문자열이 공백으로만 가득찼는지 혹은 undefined, null 값을 가지고 있으면 false, 정상적인 문자열이면 true
- decodeBase64Url : jwt 토큰을 해석할 때, 사용함.
- decodeJwt : 현재 localStorage에 있는 jwt 토큰을 해석하고 json화 시켜서 출력. 단순히 token.ID와 같이 사용하면 끝.
- adapterEvent : 예를 들어 button의 onClick과 같이 이벤트의 값을 받아서 처리해야 하는 함수가 요구될 때, event.target.value라는 값으로 이벤트 발생 시 생긴 파라미터값을 가져와야 했다. 이런 부분이 거슬려서 다이렉트로 이벤트 파라미터를 받을 수 있겠끔 어댑터 함수를 만듦.
=> #107 - 각종 유용한 utility 함수들 추가

frontend/src/ComponentsUsers/Header/index.js, frontend/src/ComponentsUsers/Mock/css.css, frontend/src/ComponentsUsers/RNW/index.js, frontend/src/ComponentsUsers/Sheet/index.js, frontend/src/ComponentsUsers/index.js
1. RNW, Sheet의 입력 방식을 props가 아니라 중구난방하게 여러 파라미터를 사용하게 했음. 이것을 props 파라미터로 바꿔서 받기로 함.
2. 기존에 미처 전역 컴포넌트로 등록하지 못해 이것을 해결하고자 함.
=> #110 - 기존 컴포넌트들 리펙토링

frontend/src/ComponentsBoard/Article/index.js, frontend/src/ComponentsBoard/Board/index.js, frontend/src/ComponentsBoard/index.js, frontend/src/routes/index.js
=> #114-게시판 기본 기능 및 기초적인 구조 구현

back_end/src/main/resources/data.sql
=> #127 - 테스트를 위한 예시 데이터 적재

frontend/src/utils/index.js
null check 이후에 str.trim() 함수를 호출햇어야 했는데 순서가 뒤바꿔서 오류를 발생함.
=> #129 - util 함수 버그 개선

frontend/src/ComponentsUsers/UserPage/Info.js, frontend/src/utils/index.js
위와 같이 **최고관리자**로 접속하면 유저 공통 페이지 상단에 **게시판관리자** 권한을 부여할 수 있는 요소가 생김.
=> Feature/#136 유저 공통 페이지 구현

back_end/src/main/resources/data.sql
유저 칼럼 email의 유일성 속성이 존재하는데
data.sql에서 이런 점이 훼손되어 서버 설정에 문제가 발생함.
중복된 데이터를 제거하고 추가로 파일을 깔끔하게 정리함.
=> #152 - data.sql 중 유저 칼럼 email의 유일성 훼손 버그 수정

frontend/package-lock.json, frontend/package.json, frontend/src/api/index.js
기존에는 각 요청마다 ID가 부여되지 않아 어떤 응답이 어떤 요청에 대한 것인지가 명확하지 않았음.
UUID를 이용해 각 요청과 응답을 구분하고 글자에 색을 부여해 가독성을 높였다.
=> #148 - JS 로그 가독성 향상

frontend/src/Header/BoardAdminAuth.js, frontend/src/Header/LogOut.js, frontend/src/Header/PrimeAdminAuth.js, frontend/src/Header/UserAuth.js, frontend/src/store/reducers/AuthReducer.js
로그아웃과 관련된 버튼을 코드 중복시킨 채로 여러 코드로 관리. 때문에 유지보수에 불리함.
1개의 파일로 관리함.
=> #146 - 로그아웃 컴포넌트 추출

back_end/src/main/java/com/chirp/community/controller/ArticleCommentController.java, back_end/src/main/java/com/chirp/community/model/ArticleCommentDto.java, back_end/src/main/java/com/chirp/community/model/request/ArticleCommentUpdateRequest.java, back_end/src/main/resources/data.sql, frontend/src/ComponentsBoard/ArticleCreatePage/indxe.js, frontend/src/ComponentsBoard/ArticlePage/index.js, frontend/src/ComponentsBoard/BoardHeader/index.js, frontend/src/ComponentsBoard/BoardPage/index.js, frontend/src/ComponentsBoard/Comment/index.css, frontend/src/ComponentsBoard/Comment/index.js
=> Feature/#120 댓글 프론트 기본구현

frontend/src/ComponentsBoard/ArticleHeader/index.js, frontend/src/ComponentsBoard/ArticlePage/index.js, frontend/src/ComponentsBoard/BoardPage/index.js, frontend/src/ComponentsBoard/Comment/index.js
* 작성자 클릭 시 유저페이지 이동(게시판, 게시글, 댓글)
* 댓글 페이지 네이션 추가
* CSS 조정
=> #174-게시판 기능 추가 구현

frontend/src/ComponentsBoard/MainPage/BoardListCom.js, frontend/src/ComponentsBoard/MainPage/CardWithThumbnail.js, frontend/src/ComponentsBoard/MainPage/IconTable.js, frontend/src/ComponentsBoard/MainPage/RandomLikeArticle.js, frontend/src/ComponentsBoard/MainPage/RecentLikeArticle.js, frontend/src/ComponentsBoard/MainPage/RecentLikeComment.js, frontend/src/ComponentsBoard/MainPage/RecentListCom.js, frontend/src/ComponentsBoard/MainPage/RisingLikeArticle.js, frontend/src/ComponentsBoard/MainPage/RisingViewArticle.js, frontend/src/ComponentsBoard/MainPage/index.js, frontend/src/ComponentsUtils/List/ListWithPageBar.js, frontend/src/ComponentsUtils/index.js
1. 추천 급상승 게시판
2. 조회수 급상승 게시판
3. 최근 게시물
4. 최근 댓글
5. 임의의 게시판 3개
작업물을 공유하기 위해 미완성 상태이지만 머지함.
=> #177 - 홈페이지 대략적 구조 잡기

frontend/src/ComponentsBoard/ArticleCreatePage/indxe.js
mode가 잘못된 대상의 값이 들어있었고,
조건문이 반대로 되어있었다.
=> #192-게시글작성 버그수정

frontend/Dockerfile, frontend/ForDockerfile/nginx.conf
React로 만든 프로그램의 서버를 구동시키는 docker 이미지 빌드. Nginx를 이용해서 웹서버 구축.
- Dockerfile 생성.
- nginx.conf 생성.
=> #197 - Web Server 도커 이미지 빌드

back_end/Dockerfile
#199-백엔드 도커파일 생성 및 이미지 생성, 동작 확인
=> #199-백엔드 도커파일 생성 및 이미지 생성, 동작 확인

back_end/docker-compose.yml, frontend/ForDockerfile/nginx.conf, frontend/src/utils/index.js
서버 구축을 위한 Docker-Compose 설정
1. 백엔드 서버 이미지
2. 프론트엔드 서버 이미지
3. MySQL 서버 이미지
4. Redis 서버 이미지
=> #201 - 서버 구성을 위한 Docker-Compose 설정

.github/workflows/build-push-docker.yml
=> #206 - 배포 자동화 설정

back_end/.gitignore, back_end/build.gradle, back_end/src/main/java/com/chirp/community/CommunityApplication.java, back_end/src/main/java/com/chirp/community/aspect/LoggingAspect.java, back_end/src/main/java/com/chirp/community/configuration/AuthenticationConfig.java, back_end/src/main/java/com/chirp/community/configuration/filter/HttpRequestSessionIdRepositoryFilter.java, back_end/src/main/java/com/chirp/community/configuration/filter/LoggingFilter.java, back_end/src/main/java/com/chirp/community/configuration/filter/PageSessionIdRepositoryFilter.java, back_end/src/main/java/com/chirp/community/configuration/filter/SessionIdRepositoryFilter.java, back_end/src/main/java/com/chirp/community/utils/LogUtils.java, back_end/src/main/java/com/chirp/community/utils/SessionIdLogUtils.java, back_end/src/main/resources/application-jpa.yml, back_end/src/main/resources/application-log.yml, back_end/src/main/resources/application-security.yml, back_end/src/main/resources/application.yml, back_end/src/main/resources/logback-jpa.xml, back_end/src/main/resources/logback-log.xml, back_end/src/main/resources/logback-security.xml, back_end/src/main/resources/logback-spring.xml, frontend/src/api/index.js, frontend/src/routes/RouteProxy.js, frontend/src/routes/index.js, frontend/src/utils/index.js
백엔드의 성능을 수치화하기 위해 api 성능을 측정할 장치들을 생성.
차후 리펙토링의 근거로 사용할 예정.
=> Feature/#175 각 api 성능 측정

back_end/src/main/java/com/chirp/community/configuration/JwtConfig.java, back_end/src/main/java/com/chirp/community/service/AuthServiceImpl.java, back_end/src/main/java/com/chirp/community/utils/JwtTokenWithRS256Utils.java
비효율적인 JWT 페이로드 설정 구조로 인해 관련 코드를 수정.
=> #223 - JWT payload 관련 설정 코드 리펙토링

back_end/src/main/java/com/chirp/community/properties/VerificationCodeProperties.java, back_end/src/main/java/com/chirp/community/service/AuthServiceImpl.java, back_end/src/main/java/com/chirp/community/utils/EmailContentUtils.java, back_end/src/main/resources/application-email-local.yml, back_end/src/main/resources/application-email-prod.yml, back_end/src/main/resources/application.yml
이메일 인증을 진행할 때, 이메일 인증 링크의 리다이렉션 url은
frontend url에 따라 다르기 때문에 이것을 application.yml 파일로 관리하고자 한다.
=> #232 - 분리된 profile에 대한 이메일 설정

back_end/src/main/java/com/chirp/community/repository/ArticleCommentRepository.java, back_end/src/main/java/com/chirp/community/repository/ArticleRepository.java
페이지바의 전체 페이지를 전달하기 위해 count query 작성.
=> Feature/#221 페이지 바 기능을 위한 count query 작성
