- back_end/src/main/java/com/chirp/community/exception/CommunityException.java
- back_end/src/main/java/com/chirp/community/repository/BoardRepository.java
- back_end/src/main/java/com/chirp/community/service/BoardServiceImpl.java
1. BoardServiceImpl.readAllByKeyword의 경우, keyword가 존재하지 않으면 단순히 모든 엔티티를 로드하는 방식으로 구현.
2. BoardServiceImpl.readById의 경우, 존재하지 않는 id가 요구되면 에러를 발생시키기로 구현.
3. create, update 모두 오류없이 수행되면 생성 혹은 수정의 결과를 클라이언트에게 전달함.
CommunityException는 RuntimeException를 상속받고 있으며 3개의 필드를 가진다. 
1 번째는 클라이언트에게 전달할 httpStatus
2 번째는 클라이언트에게 전달할 오류 메세지
3 번째는 서버 로그에 기록할 오류 메세지
> #14 - BoardService 및 BoardRepository 생성

- back_end/src/main/java/com/chirp/community/exception/ExceptionHandlerController.java
- 일괄 오류 처리의 필요성.
한 두개의 API에 대해서 오류 처리를 수행해야 한다면 try-catch 문을 이용해서 수행하면 되겠지만
수 십개의 API에 대한 오류를 처리하려면 프록시 패턴을 이용해서 오류처리를 하는 것이 필요하다.
이를 위해 Spring에서는 AOP 기능을 제공하고 있고
그 구현체 중 하나인 ControllerAdvice를 이용해서
Controller Layer의 일괄 오류 처리를 수행하고자 한다.
- 현 프로젝트에서의 적용법
httpStatus와 descriptionForClient는 Client에게 전달할 오류 메세지고
descriptionForServer는 Server Logging System에 전달할 오류 메세지다.
따라서, warn 수준의 log로 descriptionForServer를 찍게하고 그 외의 데이터를 클라이언트에게 오류 메세지로 전달한다.
> #16 - 일괄 오류 처리의 필요성.

- back_end/build.gradle
- back_end/src/main/java/com/chirp/community/entity/SiteUser.java
- back_end/src/main/java/com/chirp/community/exception/ExceptionHandlerController.java
- back_end/src/main/java/com/chirp/community/repository/SiteUserRepository.java
- back_end/src/main/java/com/chirp/community/service/SiteUserServiceImpl.java
- back_end/src/main/java/com/chirp/community/utils/ConvertRequestToMap.java
- back_end/src/test/java/com/chirp/community/exception/ExceptionHandlerControllerTest.java
- back_end/src/test/java/com/chirp/community/repository/SiteUserRepositoryTest.java
- back_end/src/test/java/com/chirp/community/utils/SetProfile.java
각 칼럼 중에 Unique, Not Null 조건을 위반할 때, 처리를 Service Layer에서 하지 않고 Repository Layer에서 처리하도록 의도함. 만약 Service Layer에서 처리하게 된다면 예를 들자면 Unique 제한 조건을 지닌 email 칼럼에 특정 값이 들어올 때, 이 email이 존재하는지 확인하려면 DB에 insert 쿼리 뿐만 아니라 select 쿼리도 추가로 보내야 한다. 이는 트래픽을 몇 배로 늘리는 행위이므로 이를 DB 내에서 처리되도록 Repository Layer에서 발생하는 Error를 처리하는 방식을 사용하기로 함. 위 상황처럼 칼럼 제한 조건 위반 에러가 뜰 때, 이를 처리하는 로직을 ExceptionHandlerController에 추가. SiteUserServiceImpl와 SiteUserRepository 작성.
위 상황을 해결한 로직을 확인하는 Test Code작성.
> #21 - SiteUserService 및 SiteUserRepository 구현

- back_end/build.gradle
- back_end/src/main/java/com/chirp/community/configuration/AsymmetricKeyConfig.java
- back_end/src/main/java/com/chirp/community/configuration/AuthenticationConfig.java
- back_end/src/main/java/com/chirp/community/configuration/CorsConfig.java
- back_end/src/main/java/com/chirp/community/configuration/PasswordEncodeConfig.java
- back_end/src/main/java/com/chirp/community/configuration/filter/JwtFilter.java
- back_end/src/main/java/com/chirp/community/exception/CommunityAccessDeniedHandler.java
- back_end/src/main/java/com/chirp/community/exception/CommunityAuthenticationEntryPoint.java
- back_end/src/main/java/com/chirp/community/model/SiteUserDto.java
- back_end/src/main/java/com/chirp/community/properties/CorsProperties.java
- back_end/src/main/java/com/chirp/community/properties/JwtProperties.java
- back_end/src/main/java/com/chirp/community/repository/SiteUserRepository.java
- back_end/src/main/java/com/chirp/community/service/SiteUserService.java
- back_end/src/main/java/com/chirp/community/service/SiteUserServiceImpl.java
- back_end/src/main/java/com/chirp/community/type/RoleType.java
- back_end/src/main/java/com/chirp/community/utils/JwtFilterUtils.java
- back_end/src/main/java/com/chirp/community/utils/JwtTokenWithRS256Utils.java
- back_end/src/main/resources/application-cors.yml
- back_end/src/main/resources/application-jwt.yml
- back_end/src/main/resources/application.yml
#32 - Spring Security 설정
1. build.gradle 에 spring-boot-starter-security과 jjwt 관련 의존성을 추가.
2. application-jwt.yml, application-cors.yml 설정 파일을 작성하고 application.yml 파일에서 인식할 수 있도록 수정.
3. AuthenticationConfig 작성. API 서버를 구축한다는 점을 유념하여 각종 보안 사항들을 설정. 하지만 인가에 대한 설정[authorizeHttpRequests 관련 설정]은 아직 세부적으로 구성하지 못함. 차후에 수정하도록 해야 함.
4. CommunityAuthenticationEntryPoint, CommunityAccessDeniedHandler 설정을 수행해 인증, 인가 오류 시, 문제를 해결함.
5. CORS, AsymmetricKey 관련 설정을 각각 CorsConfig, AsymmetricKeyConfig을 통해 수행함.
6. CORS, AsymmetricKey 관련 설정을 위한 Properties를 각각 CorsProperties, JwtProperties를 이용해 설정함.
7. Jwt 토큰을 이용한 인증, 인가 기능을 구현하기 위해 JwtFilter 작성. 이 때, 가독성을 위해 JwtTokenWithRS256Utils, JwtFilterUtils 라는 클래스들을 통해 내용을 분산시켰는데 나눈 기준은 각각 'RS256를 사용하는 Jwt 프로젝트에서 범용적으로 사용되는 함수들', '이번 프로젝트에 종속적인 함수들'이라는 프로젝트 종속성을 기준으로 …
> Feature/#32 spring security 설정

- back_end/src/main/java/com/chirp/community/configuration/JpaAuditingConfig.java
- back_end/src/main/java/com/chirp/community/entity/Board.java
- back_end/src/main/java/com/chirp/community/entity/SiteUser.java
1. JpaAuditingConfig 설정을 통해 AuditorAware<> 재정의.
2. 각 도메인이 AuditingEntityListener를 적용할 수 있게 @EntityListeners(AuditingEntityListener.class) 어노테이션을 추가함.
> #34 - Jpa Auditing 기능 구현

- back_end/src/main/java/com/chirp/community/entity/Board.java
- back_end/src/main/java/com/chirp/community/entity/SiteUser.java
1. SiteUser
- 유저 검색 시, 로그인 과정으로 인해 email 칼럼에 대한 조회가 빈번하게 발생함. 따라서 해당 칼럼을 인덱스로 설정.
2. Board
- 게시판 검색 시, 검색 기능으로 인해 name 칼럼에 대한 조회가 빈번하게 발생함. 따라서 해당 칼럼을 인덱스로 설정.
> #34 - 도메인 별 DB Index 추가

- back_end/src/main/java/com/chirp/community/service/BoardServiceImpl.java
- back_end/src/main/java/com/chirp/community/service/SiteUserServiceImpl.java
1. 기존 코드는 email, password가 null값이어도 통짜로 덮어쓰기 때문에 특별히 수정을 요구하지 않은 부분도 수정토록했다. 이런 문제점으로 인해 들어온 값이 null값이 아닐 경우에만 덮어쓰도록 수정함.
2. BoardServiceImpl 경우에도 차후에 칼럼이 추가됨에 따라 비슷한 문제를 겪을 수 있으므로 예방차원에서 코드 수정.
> #38 - SiterUser 도메인 update 기능 디버깅

- back_end/src/main/java/com/chirp/community/controller/ArticleController.java
- back_end/src/main/java/com/chirp/community/controller/BoardController.java
- back_end/src/main/java/com/chirp/community/controller/SiteUserController.java
- back_end/src/main/java/com/chirp/community/entity/Article.java
- back_end/src/main/java/com/chirp/community/model/ArticleDto.java
- back_end/src/main/java/com/chirp/community/model/request/ArticleCreateRequest.java
- back_end/src/main/java/com/chirp/community/model/request/ArticleUpdateRequest.java
- back_end/src/main/java/com/chirp/community/model/response/ArticleReadResponse.java
- back_end/src/main/java/com/chirp/community/model/response/ArticleReadRowResponse.java
- back_end/src/main/java/com/chirp/community/model/response/SiteUserReadRowResponse.java
- back_end/src/main/java/com/chirp/community/repository/ArticleRepository.java
- back_end/src/main/java/com/chirp/community/service/ArticleService.java
- back_end/src/main/java/com/chirp/community/service/ArticleServiceImpl.java
#23 - 게시물 도메인 설계
1. article의 각 칼럼은 ID(고유 번호), CreatedAt(생성 일자), Board_id(게시판 ID), Title(제목), Writer_id(작성자 ID), Content(글 내용), Views(조회수)를 의미한다.
#25 - ArticleController 및 DTO 생성
1. ArticleController 를 통해 CRUD와 같은 기본적인 기능 구현.
2. ArticleCreateRequest, ArticleUpdateRequest, ArticleDto를 구현해 각 상황에서 요구하는 정보만 클라이언트에 전송하게 끔 설계.
3. 조회 기능을 위한 DTO 설계 시, 2가지로 나눠 설계를 진행함. ArticleReadResponse, ArticleReadRowResponse로 각각 나눴는데 그 이유는 전자는 게시물 페이지 열람 시, 게시물의 대부분의 칼럼을 노출 시켜야 하기 때문에 설계했고 후자는 게시물 목록을 띄울 때, 필요한 칼럼만 기입했다.
4. ArticleService 인터페이스 설계.
#26 - ArticleServiceImpl 및 ArticleRepository 생성
1. ArticleController의 요구사항에 맞춰 각 클래스를 구성.
#40 - Article 도메인 추가로 인한 SiteUserController와 BoardController의 추가 사항
1. SiteUserController에서 [GET] /api/v1/user/{id}/article API를 추가할 수 있게 됨.
2. BoardController에서 [GET] …
> Feature/#24 article 도메인 관련 api 구현

- back_end/src/main/java/com/chirp/community/configuration/AuthenticationConfig.java
- 기존의 문제점
1. Spring Security에 의해 몇몇 가지 보안 장치가 h2 console의 사용을 방해하고 있어 그 점을 해결함.
2. h2의 frame 사용으로 인해 clickjacking을 막는 장치인 X-Frame-Options csrf 토큰을 제공하지 않는 h2 console로 인한 csrf 토큰 문제.
- 해결 방안
1. X-Frame-Options 헤더의 값을 sameorigin을 설정.
2. csrf의 ignoringRequestMatchers 설정을 통해 특정 URL로의 접근은 csrf 토큰 제출을 생략함.
> #47 - h2 console을 사용하기 위한 추가 설정

- back_end/src/main/resources/application-h2db.yml
- 기존의 문제점 spring.sql.init.mode 설정을 하지 않아 sql 초기화가 이뤄지지 않았음.
- 해결 방안 application-h2db.yml 중 spring.sql.init.mode=always 설정을 수행.
> #49 - hdata.sql 적용 불가 문제 해결

- back_end/src/main/java/com/chirp/community/entity/SiteUser.java
- 기존의 문제점 role 칼럼에 대해 입력값이 존재하지 않는다면 USER라는 값을 기본값으로 부여하기로 하였다. 하지만 실제로 초기화되는 값은 'chirp-team'이라는 값으로 USER라는 값이 이스케이프되지 않고 그대로 SQL문에 사용돼 chirp-team라는 데이터베이스의 유저명이 입력된 것이었다.
- 해결 방안 쌍따옴표 안에 따옴표를 덧대 문자열임을 명시하였다.
> #51 - site_user 도메인 초기화 버그

- back_end/src/main/java/com/chirp/community/CommunityApplication.java
- 기존의 문제점 @CreatedDate가 포함된 엔티티를 새로 생성해도 null값으로 나옴
- 해결 방안 CommunityApplication에 @EnableJpaAuditing를 포함시키지 못했음. 이를 수정.
> #53 - @CreatedDate 가 작동하지 않는 버그

- back_end/src/main/java/com/chirp/community/configuration/CorsConfig.java
- back_end/src/main/resources/application-cors.yml
- 기존의 문제점 React 서버의 포트를 몰라 포트를 정하지 않아 프론트와의 Cors 문제가 야기됨.
- 해결 방법 localhost:3000로 정해놓았다.
> #64 - Cors Origin 결정

- back_end/src/main/java/com/chirp/community/entity/SiteUser.java
- 기존의 문제점 @Enumerated(EnumType.STRING)는 enum의 name()에 해당하는 부분만 처리하지 Converter의 내용을 수용하지 않는다.
- 해결 방법 @convert(converter = RoleType.ConverterImpl.class)로 치환해 정의한 Converter를 적용함.
> #66 - SiteUser의 role 칼럼의 Convert 문제 해결

- back_end/src/main/java/com/chirp/community/controller/AuthController.java
- back_end/src/main/java/com/chirp/community/model/request/AuthRequest.java
- back_end/src/main/java/com/chirp/community/model/response/AuthReadResponse.java
- back_end/src/main/java/com/chirp/community/service/AuthService.java
- back_end/src/main/java/com/chirp/community/service/AuthServiceImpl.java
- AuthController 구현 이메일과 비밀번호를 제공하면 인증 후 JWT를 발급하는 API 구현
- AuthService 구현 총 세단계로 구분할 수 있다.
1. DB에서 email을 이용해 엔티티 조회
2. 해당 엔티티의 비밀번호와 입력된 비밀번호를 비교
3. 모두 완료되면 JWT를 발급.
> #68 - 로그인 시 토큰을 발급해주는 API 구현

- back_end/src/main/java/com/chirp/community/exception/CommunityAccessDeniedHandler.java
- back_end/src/main/java/com/chirp/community/exception/CommunityAuthenticationEntryPoint.java
- back_end/src/main/java/com/chirp/community/exception/ExceptionHandlerController.java
- back_end/src/main/java/com/chirp/community/model/response/ErrorResponse.java
- 도입 계기 사용자에게 로그인 실패 시, 실패 이유에 대해 알려주기 위한 에러 처리가 필요하다. 이런 일들을 수행하기 위해 에러 메시지의 전송 형태를 json 형식으로 하는 것이 용이할 것이란 판단하에 수정하게 됨.
> #72 - 에러 응답 전송 시 Json 형식으로 전송

- back_end/src/main/java/com/chirp/community/controller/BoardController.java
기존에는 keyword의 기본값이 정해지지 않아 service Layer에서의 keyword.isBlank() 함수에서 문제가 발생했었다.
BoardController.readAllByKeyword 메서드의 파라미터를
@RequestParam String keyword 에서
@RequestParam(defaultValue = "") String keyword 로 변경했다.
> #78 - BoardController.readAllByKeyword 파라미터인 keyword의 초기값 지정

- back_end/src/main/java/com/chirp/community/service/SiteUserServiceImpl.java
- back_end/src/main/java/com/chirp/community/utils/CheckTools.java
- frontend/src/ComponentsUsers/SignUp/css.css
- frontend/src/ComponentsUsers/SignUp/index.js
- frontend/src/ComponentsUsers/index.js
- frontend/src/routes/index.js
1. '비밀 번호'와 '비밀 번호 재확인' 입력이 다르면 아예 쿼리를 보내지않고 에러메세지를 띄움.
2. 동일한 이메일 혹은 동일한 닉네임은 계정 생성을 거부함.
3. 빈 칸으로 제출 시, 계정 생성 거부.
4. 계정 생성 성공 시, 로그인 화면으로 이동.
5. 백엔드에서 빈칸으로 제출된 경우를 필터링하기 위한 장치 마련. [SiteUserServiceImpl.create] [CheckTools.nullCheck]
> #87 - 회원 가입 페이지 생성

- back_end/src/main/java/com/chirp/community/configuration/AuthenticationConfig.java
서버에서 csrf 토큰을 쿠키에 저장하고 클라이언트에서 쿠키에 담긴 토큰을 헤더 'X-XSRF-TOKEN'에 넣어 보내면 인증이 되는 시스템. 서버의 문제로 인해 한 번은 쿠키에 csrf 토큰을 담아서 건네주고 그 다음 한 번 csrf 토큰을 말소시키는 쿠키를 넣어 보내면서 '인가 오류'가 2번 중 1번 꼴로 발생하기에 이름
해당 문제를 찾아봐도 해결되지 않아 잠정적으로 csrf 보안을 꺼두기로 결정.
> #90 - csrf 보안 잠정 중단

- frontend/package-lock.json
- frontend/package.json
- frontend/src/Header/css.css
- frontend/src/Header/index.js
- frontend/src/routes/index.js
* ComponentsBoard 폴더 추가 : 게시판 관련 페이지 컴포넌트 정리구역
* 통합 Header, Footer 폴더 추가 : 전체 페이지에 적용되는 헤더, 푸터 작업을 위한 폴더 생성
* 위의 변경들에 의한 import 좌표 수정 및, 라우터 Header 태그 import 대상을 메인(전체페이지)헤더로 변경
> #59-프론트엔드 파일구조 변경

- back_end/src/main/java/com/chirp/community/configuration/JwtConfig.java
- back_end/src/main/java/com/chirp/community/service/AuthServiceImpl.java
- back_end/src/main/java/com/chirp/community/type/RoleType.java
- back_end/src/main/java/com/chirp/community/utils/ConvertToJwtClaims.java
- back_end/src/main/java/com/chirp/community/utils/JwtTokenWithRS256Utils.java
유저 페이지에서 로그인 유저의 페이지의 내용을 로드하기 위해 DB에 유저 정보를 로드할 수도 있지만 JWT의 장점을 살려 인증 정보를 이용해 id값을 가져올 수 있도록 한다.
1. claim 구조를 설정할 수 있는 JwtConfig를 만들어 설정할 수 있게함.
2. 기존에 주입하던 sub, iss, exp 등 위에 직접 정의한 내용을 추가로 얹을 수 있게 만듦.
3. RoleType에 JWT에 추가할 jwtName 필드를 추가로 정의함.
4. payload에 ID값, Nickname, role값을 추가로 넣어둠.
> #98 - JWT claim 내용 추가

- frontend/src/ComponentsUsers/RNW/css.css
- frontend/src/ComponentsUsers/RNW/index.js
readonly 속성을 이용해서 true면 읽기만 가능한 label 요소가 되지만 false면 입력 가능한 input 요소로 바뀌는 컴포넌트를 제작.
> #102 - RNW 컴포넌트 생성

- back_end/src/main/java/com/chirp/community/entity/Article.java
- back_end/src/main/java/com/chirp/community/entity/Board.java
- back_end/src/main/java/com/chirp/community/entity/SiteUser.java
기존에선 SiteUser와 Article이 양방향 연관관계를 맺을 때, SiteUser 엔티티가 삭제될 때, 연관 Article들이 자동으로 삭제되게 했었다. 하지만 역방향으로 설계되어 Article이 삭제되면 SiteUser가 삭제되는 버그가 생겼다. 또한 Board와 Article의 관계도 그러햇다.
CascadeType 설정을 역방향으로 바꿈.
> #123 - 잘못된 CascadeType 교정

- frontend/src/ComponentsUsers/Login/index.js
- frontend/src/ComponentsUsers/SignUp/index.js
- frontend/src/api/index.js
1. 요청, 응답의 header, body를 각각 표현함.
2. 어떤 URI의 어떤 Method를 이용해서 요청을 하는 지도 Logging
3. 프록시 기능에 따라 .then()을 분리시킴. [가독성을 위해 기능 별 코드 분리.]
4. json으로 응답을 받지 못하는 객체는 response.text()로 글자 그대로 가져오게 함.
5. 불필요한 들여쓰기 일괄 삭제.
> #125 - src/api/index.js 내용 보완

- back_end/src/main/java/com/chirp/community/service/SiteUserServiceImpl.java
- back_end/src/main/java/com/chirp/community/utils/AccessAuthorizer.java
유저 정보를 수정할 수 있는 주체는 최고 관리자와 당사자다.
하지만 최고 관리자가 수정을 할 때 인가 문제가 발생했다.
분석 결과 코드 오류가 존재해 해당 부분을 교정함.
해당 부분을 교정함.
> #150 - 유저 정보 업데이트 시 최고 관리자 인식 불가 버그 수정

- frontend/src/ComponentsUsers/BoardDashBoard/BoardList.js
- frontend/src/store/actions/AuthAction.js
- frontend/src/store/index.js
- frontend/src/store/util.js
페이지를 새로고침하게 되면 기존에 존재했던 State들이 모두 초기화되고 이렇게 되면 로그인 기록이 말소된다. 때문에 이것을 막기 위해 상태에 변화가 감지될 때마다 LocalStorage에 상태를 일괄 저장한다.
Store의 Subcribe를 이용해서
상태에 변화가 감지될 때마다 LocalStorage에 상태를 일괄 저장한다.
> #144 - Redux 영속성 부여

- back_end/.gitignore
- back_end/src/main/java/com/chirp/community/configuration/AuthenticationConfig.java
- back_end/src/main/java/com/chirp/community/controller/AuthController.java
- back_end/src/main/java/com/chirp/community/controller/SiteUserController.java
- back_end/src/main/java/com/chirp/community/model/request/SiteUserUpdateRequest.java
- back_end/src/main/java/com/chirp/community/service/ArticleServiceImpl.java
- back_end/src/main/java/com/chirp/community/service/AuthService.java
- back_end/src/main/java/com/chirp/community/service/AuthServiceImpl.java
- back_end/src/main/java/com/chirp/community/service/SiteUserService.java
- back_end/src/main/java/com/chirp/community/service/SiteUserServiceImpl.java
- frontend/src/ComponentsUsers/EmailVerification/MustBeVerifiedCom.js
- frontend/src/ComponentsUsers/EmailVerification/index.js
- frontend/src/ComponentsUsers/Login/index.js
- frontend/src/ComponentsUsers/UserPage/Info.js
1. gitignore에 application-emailsecurity.yml 내용 추가.
2. 프론트에서 이메일 인증 컴포넌트가 비활성화될 때, 확실한 은신 상태 유지.
3. 명확한 의미를 위해 /api/v1/auth/login => /api/v1/auth/access_token으로 변경.
4. 유저 지위를 변경하는 api를 오직 관리자만 가능하도록 보안 설정을 하고 
/api/v1/user/*/role/user, /api/v1/user/*/role/user_verified_by_email, /api/v1/user/*/role/board_admin 을 추가.
5. 명확한 의미를 위해 GET /api/v1/auth/email_verification_code => PATCH /api/v1/user/*/role/user_verified_by_email로 변경.
6. 게시물을 조회할 때마다 조회수를 올리는 로직 추가.
> Feature/#160 각종 버그 수정

- back_end/src/main/java/com/chirp/community/controller/BoardController.java
- back_end/src/main/java/com/chirp/community/controller/SiteUserController.java
- back_end/src/main/java/com/chirp/community/model/ArticleDto.java
- back_end/src/main/java/com/chirp/community/model/response/ArticleReadBoardPageRowResponse.java
- back_end/src/main/java/com/chirp/community/model/response/ArticleReadMyPageRowResponse.java
- back_end/src/main/java/com/chirp/community/repository/ArticleRepository.java
- back_end/src/main/java/com/chirp/community/service/ArticleServiceImpl.java
- frontend/src/ComponentsBoard/BoardPage/index.js
- frontend/src/ComponentsUsers/UserPageCom/ArticleList.js
- frontend/src/ComponentsUsers/UserPageCom/CommentList.js
기존의 연관 관계에서는 Lazy Loading을 이용해서 필요없는 연관관계를 호출하지 않도록 의도했다. 하지만 XXXDto.fromEntity 내부에 .getXXX() 와 같이 프록시 엔티티 객체의 의도하지 않은 Lazy Loading을 유발해. 불필요한 로딩을 야기하는 문제가 발생했다.
XXXDto.fromEntity 내부에서 연관 관계에 놓여 있는 객체를 함부러 호출하지 않고 toBuilder를 이용해서 데이터를 추가하는 형태로 유도함.
> #162 - XXXDto.fromEntity에 의한 Lazy Loading 버그

- back_end/src/main/java/com/chirp/community/controller/ArticleCommentController.java
- back_end/src/main/java/com/chirp/community/model/ArticleCommentDto.java
- back_end/src/main/java/com/chirp/community/repository/ArticleCommentRepository.java
- back_end/src/main/java/com/chirp/community/service/ArticleCommentService.java
- back_end/src/main/java/com/chirp/community/service/ArticleCommentServiceImpl.java
- back_end/src/main/resources/data.sql
- frontend/src/ComponentsUsers/UserPageCom/ArticleList.js
- frontend/src/ComponentsUsers/UserPageCom/CommentList.js
기존의 연관 관계에서는 Lazy Loading을 이용해서 필요없는 연관관계를 호출하지 않도록 의도했다. 하지만 XXXDto.fromEntity 내부에 .getXXX() 와 같이 프록시 엔티티 객체의 의도하지 않은 Lazy Loading을 유발해. 불필요한 로딩을 야기하는 문제가 발생했다.
XXXDto.fromEntity 내부에서 연관 관계에 놓여 있는 객체를 함부러 호출하지 않고 toBuilder를 이용해서 데이터를 추가하는 형태로 유도함.
> #164 - MyPage 댓글 목록 로드 기능 구현

- back_end/src/main/java/com/chirp/community/service/SiteUserServiceImpl.java
- frontend/src/store/reducers/AuthReducer.js
개인 정보 수정란에서 이메일값을 바꿔도 기존에 이메일 인증 유저라면 바뀐 이메일에 대해서도 인증 유저라고 뜨는 상황으로 인해 악용 가능성이 있을 수 있다.
정보 수정 시, 기존의 이메일과 다르다면 인증 상태가 풀리도록 설정.
> #169 - 개인 정보 수정 시 이메일 변경에도 이메일 인증으로 뜨는 버그 수정

- back_end/src/main/java/com/chirp/community/controller/ArticleCommentController.java
- back_end/src/main/java/com/chirp/community/entity/ArticleCommentLikes.java
- back_end/src/main/java/com/chirp/community/repository/ArticleCommentLikesRepository.java
- back_end/src/main/java/com/chirp/community/service/ArticleCommentLikesService.java
- back_end/src/main/java/com/chirp/community/service/ArticleCommentLikesServiceImpl.java
- back_end/src/main/resources/data.sql
- back_end/src/main/resources/mysql_schema.sql
- frontend/src/ComponentsBoard/Comment/index.js
- frontend/src/ComponentsUtils/LikesComSm/BtnDisLikes.js
- frontend/src/ComponentsUtils/LikesComSm/BtnLikes.js
- frontend/src/ComponentsUtils/LikesComSm/Label.js
- frontend/src/ComponentsUtils/LikesComSm/css.css
- frontend/src/ComponentsUtils/LikesComSm/index.js
- frontend/src/ComponentsUtils/index.js
댓글에서의 추천 기능 구현.
특정 사람이 특정 댓글에는 1번만 추천 가능하고 다시 누르면 취소되는 형태다.
추천과 비추천을 구분하지 않고 value값을 집어 넣어서
추천 시, value=1이 되고 비추천 시, value=-1이 된다.
#구현 형태.
- 추천수 0인 상태 ![image](https://github.com/chirp-community/chirp-community/assets/66674140/4274b1af-8139-4681-8170-9e6cf191a267)
- 추천수 0 이상의 상태 ![image](https://github.com/chirp-community/chirp-community/assets/66674140/47730413-70e6-44f8-933c-3371314c8d6d)
- 추천수 0 이하의 상태 ![image](https://github.com/chirp-community/chirp-community/assets/66674140/8af6aae4-b33f-4745-8da4-67380916803e)
> #171 - 댓글 추천 컴포넌트 생성

- back_end/src/main/java/com/chirp/community/controller/ArticleController.java
- back_end/src/main/java/com/chirp/community/repository/ArticleRepository.java
- back_end/src/main/java/com/chirp/community/service/ArticleService.java
- back_end/src/main/java/com/chirp/community/service/ArticleServiceImpl.java
- frontend/src/ComponentsBoard/MainPage/BoardListComBestViews.js
- frontend/src/ComponentsBoard/MainPage/RisingViewArticle.js
1. 홈페이지에서 사용할 1 주일 사이의 조회수 기준 정렬 게시물 조회 api 구현.
2. 베스트 게시물을 위한 컴포넌트를 새롭게 생성.
> #185 - 주간 최고 조회수 게시물 조회 api 구현

- back_end/src/main/java/com/chirp/community/controller/ArticleCommentController.java
- back_end/src/main/java/com/chirp/community/controller/ArticleController.java
- back_end/src/main/java/com/chirp/community/controller/BoardController.java
- back_end/src/main/java/com/chirp/community/model/response/ArticleCommentReadRecentlyResponse.java
- back_end/src/main/java/com/chirp/community/model/response/ArticleReadRecentlyResponse.java
- back_end/src/main/java/com/chirp/community/repository/BoardRepository.java
- back_end/src/main/java/com/chirp/community/service/ArticleCommentService.java
- back_end/src/main/java/com/chirp/community/service/ArticleCommentServiceImpl.java
- back_end/src/main/java/com/chirp/community/service/ArticleService.java
- back_end/src/main/java/com/chirp/community/service/ArticleServiceImpl.java
- back_end/src/main/java/com/chirp/community/service/BoardService.java
- back_end/src/main/java/com/chirp/community/service/BoardServiceImpl.java
- frontend/src/ComponentsBoard/MainPage/RecentListCom.js
1. 홈페이지의 랜덤하게 게시판을 보여주기 위해 랜덤 게시판 목록을 보여주는 api 구현
2. 최근 게시글 조회 api 구현
3. 최근 댓글 조회 api 구현
> #183 - 랜덤 게시판 목록 api 구현 및 최근 댓글 게시글 조회 api 구현

- frontend/src/ComponentsBoard/MainPage/RisingLikeArticle.js
- frontend/src/ComponentsBoard/MainPage/RisingViewArticle.js
- 추천 급상승 게시판은 최근 작성글 기준으로 나열할 이유가 없으므로 쿼리에서 해당 부분을 제거함.
> #188 - 추천 급상승 게시판 구현

- back_end/src/main/java/com/chirp/community/model/response/ArticleCommentReadRecentlyResponse.java
- frontend/src/ComponentsBoard/MainPage/RecentLikeComment.js
홈페이지의 최근 작성한 댓글 목록의 각 row를 클릭하면 해당 댓글이 작성된 게시글로 넘어가야 하는데 넘어가지 못함. 원인 분석으로 게시글의 id가 아닌 댓글 id가 입력됨을 확인.
프론트에서 올바른 데이터값을 넘겨 주도록 setData 함수를 재정비하고 백엔드 단에서 게시글 id값을 넘겨주도록 코드를 바꿈.
> #195 - 최근 작성한 댓글 목록 버그 수정

- .github/workflows/build-push-docker.yml
2개의 프로젝트를 수정할 때마다 각각을 빌드하고 배포하는 과정은 매우 손이 많이 가는 업무다. 때문에 main에 merge를 함과 동시에 빌드와 배포를 자동화하는 툴로 github action을 이용하고자 함.
1. React와 Spring 프로젝트를 빌드해 각각 [html, css, js], [jar] 파일을 만든다.
2. 각각을 DockerHub에 업로드함.
> #206 - 배포 자동화 설정

- back_end/src/main/java/com/chirp/community/entity/Article.java
- back_end/src/main/java/com/chirp/community/entity/ArticleComment.java
- back_end/src/main/resources/db/migration/mysql/V1__init_schema.sql
1. 게시물을 삭제하면 해당 게시물의 댓글들을 모두 삭제하도록 추가.
2. 댓글을 삭제하면 해당 좋아요 이력을 모두 삭제.
3. V1__init_schema.sql에 cascade 설정 추가.
> #222 - 누락된 cascade 추가

- frontend/.env.development
- frontend/.env.production
- frontend/package-lock.json
- frontend/package.json
- frontend/src/utils/index.js
React 프로젝트는 local profile에서 localhost:8080으로 쿼리를 보내야하고 prod profile에서는 localhost:80으로 쿼리를 보내야 한다.
때문에 이를 분리하기 위해 env-cmd를 사용해서 분리했다.
> #228 - React 프로젝트 환경변수 분리
